In [10]:
import numpy as np

In [11]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape , Y.shape

((4, 2), (4, 1))

In [12]:
def sig(z):
    return 1/(1+ np.exp(-z))

In [13]:
weights = 2*np.random.random((2,1))-1
bias = 2*np.random.random(1)-1
weights,bias

(array([[ 0.94172909],
        [-0.68085665]]),
 array([-0.34955733]))

In [14]:
# No hidden layers
output0 = X
output = sig(np.dot(output0,weights)+ bias)
output

array([[0.41348977],
       [0.26300385],
       [0.64386329],
       [0.4778433 ]])

In [15]:
#Hidden Layers
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((2,2))-1
wo = 2*np.random.random((2,2))-1
bo = 2*np.random.random((2,2))-1

In [ ]:
output0 = X
outputHidden =sig(np.dot(output0,wh)+bh)
output = sig(np.dot(outputHidden,wo)+ bo)
output